---------------------------------------
Begin Slurm Prolog: Jun-04-2024 16:16:48
Job ID:    260172
User ID:   shardin31
Account:   gts-jw254-coda20
Job name:  Slurmshardinpowderdayrun
Partition: cpu-small
QOS:       inferno
---------------------------------------

CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



Lmod is automatically replacing "mvapich2/2.3.6-ouywal" with "openmpi/4.1.4".

yt : [INFO     ] 2024-06-04 16:17:11,076 Global parallel computation enabled: 33 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 7 / 48
yt : [INFO     ] 2024-06-04 16:17:11,076 Global parallel computation enabled: 35 / 48
yt : [INFO     ] 2024-06-04 16:17:11,076 Global parallel computation enabled: 30 / 48
yt : [INFO     ] 2024-06-04 16:17:11,076 Global parallel computation enabled: 41 / 48
yt : [INFO     ] 2024-06-04 16:17:11,080 Global parallel computation enabled: 42 / 48
yt : [INFO     ] 2024-06-04 16:17:11,086 Global parallel computation enabled: 31 / 48
yt : [INFO     ] 2024-06-04 16:17:11,086 Global parallel computation enabled: 37 / 48
yt : [INFO     ] 2024-06-04 16:17:11,087 Global parallel computation enabled: 43 / 48
yt : [INFO     ] 2024-06-04 16:17:11,088 Global parallel computation enabled: 32 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 28 / 48
yt : [INFO     ] 2024-06-04 16:17:11,090 Global parallel computation enabled: 40 / 48
yt : [INFO     ] 2024-06-04 16:17:11,090 Global parallel computation enabled: 47 / 48
yt : [INFO     ] 2024-06-04 16:17:11,091 Global parallel computation enabled: 25 / 48
yt : [INFO     ] 2024-06-04 16:17:11,092 Global parallel computation enabled: 27 / 48
yt : [INFO     ] 2024-06-04 16:17:11,092 Global parallel computation enabled: 24 / 48
yt : [INFO     ] 2024-06-04 16:17:11,092 Global parallel computation enabled: 39 / 48
yt : [INFO     ] 2024-06-04 16:17:11,092 Global parallel computation enabled: 26 / 48
yt : [INFO     ] 2024-06-04 16:17:11,093 Global parallel computation enabled: 36 / 48
yt : [INFO     ] 2024-06-04 16:17:11,093 Global parallel computation enabled: 29 / 48
yt : [INFO     ] 2024-06-04 16:17:11,094 Global parallel computation enabled: 44 / 48
yt : [INFO     ] 2024-06-04 16:17:11,094 Global parallel computation enabled: 46 / 48
yt : [INFO     ] 2024-06-04 16:17:11,094 Global parallel computation enabled: 45 / 48
yt : [INFO     ] 2024-06-04 16:17:11,095 Global parallel computation enabled: 34 / 48
yt : [INFO     ] 2024-06-04 16:17:11,110 Global parallel computation enabled: 38 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 15 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 23 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 0 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 4 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 10 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 13 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 17 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 19 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 20 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 14 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 6 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 5 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 21 / 48
yt : [INFO     ] 2024-06-04 16:17:11,089 Global parallel computation enabled: 3 / 48
yt : [INFO     ] 2024-06-04 16:17:11,090 Global parallel computation enabled: 12 / 48
yt : [INFO     ] 2024-06-04 16:17:11,093 Global parallel computation enabled: 2 / 48
yt : [INFO     ] 2024-06-04 16:17:11,095 Global parallel computation enabled: 1 / 48
yt : [INFO     ] 2024-06-04 16:17:11,096 Global parallel computation enabled: 11 / 48
yt : [INFO     ] 2024-06-04 16:17:11,106 Global parallel computation enabled: 18 / 48
yt : [INFO     ] 2024-06-04 16:17:11,110 Global parallel computation enabled: 9 / 48
yt : [INFO     ] 2024-06-04 16:17:11,111 Global parallel computation enabled: 8 / 48
yt : [INFO     ] 2024-06-04 16:17:11,111 Global parallel computation enabled: 22 / 48
yt : [INFO     ] 2024-06-04 16:17:11,115 Global parallel computation enabled: 16 / 48
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P031 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P013 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P041 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P014 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P043 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P021 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P024 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P023 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P029 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P000 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P030 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P001 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P032 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P002 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P033 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P003 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P035 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P005 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P036 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P006 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P042 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P007 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P045 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P010 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P026 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P011 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P015 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P027 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P017 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P028 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P018 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P034 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P019 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P037 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P020 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P039 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P004 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P040 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
P013 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 13.
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P044 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
P021 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 21.
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P046 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P047 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
P000 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 0.
P031 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 31.
P005 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 5.
P041 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 41.
P010 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 10.
P043 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 43.
P014 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 14.
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
P045 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 45.
P017 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 17.
P024 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 24.
P020 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 20.
P029 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 29.
P023 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 23.
P030 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 30.
P001 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 1.
P033 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 33.
P002 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 2.
P035 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 35.
P003 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 3.
P036 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 36.
P006 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 6.
P042 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 42.
P007 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 7.
P027 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 27.
P011 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 11.
P032 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 32.
P015 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 15.
P037 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 37.
P018 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 18.
P040 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 40.
P019 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 19.
P046 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 46.
P026 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 26.
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P012 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
P028 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 28.
P034 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 34.
P012 yt : [ERROR    ] 2024-06-04 16:17:11,182 Error occurred on rank 12.
P044 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 44.
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P022 yt : [ERROR    ] 2024-06-04 16:17:11,182 NameError: name 'calculate_stellar_mass_100Myr' is not defined
P047 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 47.
P022 yt : [ERROR    ] 2024-06-04 16:17:11,182 Error occurred on rank 22.
P039 yt : [ERROR    ] 2024-06-04 16:17:11,181 Error occurred on rank 39.
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P008 yt : [ERROR    ] 2024-06-04 16:17:11,183 NameError: name 'calculate_stellar_mass_100Myr' is not defined
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P025 yt : [ERROR    ] 2024-06-04 16:17:11,181 NameError: name 'calculate_stellar_mass_100Myr' is not defined
P008 yt : [ERROR    ] 2024-06-04 16:17:11,183 Error occurred on rank 8.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 8 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
P025 yt : [ERROR    ] 2024-06-04 16:17:11,182 Error occurred on rank 25.
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P009 yt : [ERROR    ] 2024-06-04 16:17:11,183 NameError: name 'calculate_stellar_mass_100Myr' is not defined
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 14 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 20 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 23 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 5 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
P009 yt : [ERROR    ] 2024-06-04 16:17:11,183 Error occurred on rank 9.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 13 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 21 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 9 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
  File "stellar_mass.py", line 193, in <module>
    ap.add_recipe(stellar_mass_recipe, allds)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_pipeline.py", line 140, in add_recipe
    recipe(self)
  File "/storage/home/hcoda1/7/shardin31/.conda/envs/pd_environment_3/lib/python3.8/site-packages/ytree/analysis/analysis_operators.py", line 30, in __call__
    return self.function(target, *self.args, **self.kwargs)
  File "stellar_mass.py", line 147, in stellar_mass_recipe
    pipeline.add_operation(calculate_stellar_mass_100Myr)
P038 yt : [ERROR    ] 2024-06-04 16:17:11,184 NameError: name 'calculate_stellar_mass_100Myr' is not defined
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 12 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 17 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
P038 yt : [ERROR    ] 2024-06-04 16:17:11,184 Error occurred on rank 38.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 24 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 10 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 34 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 37 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 38 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 42 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 11 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 35 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 45 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 15 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 40 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 19 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 31 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 28 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
slurmstepd: error: *** STEP 260172.0 ON atl1-1-02-018-4-1 CANCELLED AT 2024-06-04T16:17:11 ***
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 33 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 3 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 30 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 36 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Additional features and improved performance (usually) by saving this arbor with "save_arbor" and reloading:
	>>> a = ytree.load("/storage/home/hcoda1/0/jw254/data/SG64-2020/rockstar_halos-jhw/trees/tree_0_0_0.dat")
	>>> fn = a.save_arbor()
	>>> a = ytree.load(fn)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 6 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 18 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
srun: error: atl1-1-02-018-18-1: tasks 24-47: Killed
srun: error: atl1-1-02-018-4-1: tasks 0-23: Killed
---------------------------------------
Begin Slurm Epilog: Jun-04-2024 16:17:11
Job ID:        260172
Array Job ID:  _4294967294
User ID:       shardin31
Account:       gts-jw254-coda20
Job name:      Slurmshardinpowderdayrun
Resources:     cpu=48,mem=100G,node=2
Rsrc Used:     cput=00:18:24,vmem=444K,walltime=00:00:23,mem=0,energy_used=0
Partition:     cpu-small
QOS:           inferno
Nodes:         atl1-1-02-018-4-1,atl1-1-02-018-18-1
---------------------------------------
